import type { TColumnType } from '../definitions/ColumnType';
import type { TFieldAggregationType } from '../definitions/FieldAggregationType';
import type { TFieldRoleType } from '../definitions/FieldRoleType';
import type { DataSource } from './DataSource';

/**
 * A field contains information about what data source it belongs to, its role, and the ability to fetch the domain values.
 *
 * @see https://help.tableau.com/current/api/embedding_api/en-us/reference/interfaces/field.html
 */
export interface Field {
  /** The type of aggregation for this field. */
  aggregation: TFieldAggregationType;

  /** The type of the column, either discrete or continuous. */
  columnType: TColumnType;

  /** The data source to which this field belongs. */
  dataSource: DataSource;

  /** User description of field, undefined if there is none. */
  description?: string;

  /** Unique string representing this field in this datasource. */
  id: string;

  /** True if this field is a table calculation. */
  isCalculatedField: boolean;

  /** True if this field is a combination of multiple fields, false otherwise. */
  isCombinedField: boolean;

  /** True if this field is generated by Tableau, false otherwise. Tableau generates a number of fields for a data source, such as Number of Records, or Measure Values. This property can be used to distinguish between those fields and fields that come from the underlying data connection, or were created by a user. */
  isGenerated: boolean;

  /** True if this field is hidden, false otherwise. */
  isHidden: boolean;

  /** The name of the field (i.e. the caption). */
  name: string;

  /** The role of this field. */
  role: TFieldRoleType;
}
